### ISSUE TITLE
history_effects ordered by id ?

### ISSUE THREAD

**Issue by FredericHeem** [stellar/horizon-importer#60]
The [fork](https://github.com/FinclusionSystems/open-core) of open-core is meteor app that displays real time uptime from the stellar and horizon db. Very useful for debugging. 
The effect table is not updated in real time because this table is not ordered by an id or a timestamp. 
Would it be possible to add id or a timestamp to the *history_effects* table or is it possible to tweak to [sql query](https://github.com/FinclusionSystems/open-core/blob/master/server/connect-history.coffee) to avoid adding another row ?

**Comment by nullstyle** [comment]
The `[history_operation_id, order]` pair defines the total order of application for effects.  For example, to get a list of effects order by time ascending:

```sql
SELECT *
FROM history_effects
ORDER BY history_operation_id ASC, "order" ASC
```

**Comment by FredericHeem** [comment]
Unfortunately, this query doesn't order effects by time descending.

**Comment by nullstyle** [comment]
I don't understand, why would the following not work?

```sql
SELECT *
FROM history_effects
ORDER BY history_operation_id DESC, "order" DESC
```
